"""add_pet_avatar_fields

Revision ID: 05c813854496
Revises: e95c3b202a5f
Create Date: 2026-06-19 12:54:26.960086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c813854496'
down_revision: Union[str, None] = 'e95c3b202a5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('avatar_type', sa.String(), nullable=True))
    op.add_column('pets', sa.Column('avatar_value', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'avatar_value')
    op.drop_column('pets', 'avatar_type')
    # ### end Alembic commands ###
